all: test

test: $(TEST_ELF)
	$(VMOD)$(TEST_ELF)
	
clean:
	$(RM) -rf $(DIR_OUT)

$(DIR_OUT)/uc/%.o: $(DIR_UC)/src/%.c
	$(MKDIR) -p $(@D)
	$(ECHO) "[Compiling] $(@F)"
	$(CC) -c $(CPPFLAGS) $(CFLAGS) -o $@ $<

$(DIR_OUT)/gtest/gtest-all.opp:
	$(MKDIR) -p $(@D)
	$(ECHO) "[Compiling] $(@F)"
	$(CPP) -c $(CPPFLAGS) $(CXXFLAGS) -o $@ $(DIR_GTEST)/src/gtest-all.cc
	
$(DIR_OUT)/common/main.opp:
	$(MKDIR) -p $(@D)
	$(ECHO) "[Compiling] $(@F)"
	$(CPP) -c $(CPPFLAGS) $(CXXFLAGS) -o $@ $(DIR_COMMON)/src/main.cpp
	
$(TEST_ELF): $(OBJS)
	$(CPP) -o $@ $(OBJS) $(LDFLAGS)