DIR_CURRENT := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

DIR_INC     := $(shell pwd)/include
DIR_SRC     := $(shell pwd)/src
DIR_OUT     := $(shell pwd)/out/

ifeq ($(V),1)
 VMOD :=
else
 VMOD := @
endif

MKDIR := $(VMOD)mkdir
RM    := $(VMOD)rm
ECHO  := $(VMOD)echo

CPP := $(VMOD)g++
CC  := $(VMOD)gcc

DIR_GTEST  := $(DIR_CURRENT)/googletest/googletest
DIR_COMMON := $(DIR_CURRENT)/common
DIR_UC     := $(DIR_CURRENT)/../

OBJS_GTEST  := $(DIR_OUT)/gtest/gtest-all.opp
OBJS_COMMON := $(DIR_OUT)/common/main.opp

SRCS_UC := $(shell find $(DIR_UC)/src/ -name *.c)
OBJS_UC := $(patsubst $(DIR_UC)/src/%.c, $(DIR_OUT)/uc/%.o, $(SRCS_UC))

SRCS_TEST_C   := $(shell find $(DIR_SRC) -name *.c)
SRCS_TEST_CPP := $(shell find $(DIR_SRC) -name *.cpp)
OBJS_TEST := $(patsubst $(DIR_SRC)/%.c,   $(DIR_OUT)/test/%.o,   $(SRCS_TEST_C))
OBJS_TEST += $(patsubst $(DIR_SRC)/%.cpp, $(DIR_OUT)/test/%.opp, $(SRCS_TEST_CPP))

OBJS := $(OBJS_GTEST) $(OBJS_COMMON) $(OBJS_UC) $(OBJS_TEST)

TEST_ELF := $(DIR_OUT)/test.elf

CPPFLAGS += -I$(DIR_GTEST)/include -I$(DIR_GTEST) -I$(DIR_UC)/include
CXXFLAGS += -g -Wall -Wextra -pthread
LDFLAGS  += -lpthread
